x11/kitty: Update to 0.35.2
- Pet portfmt
- Add a couple of patches to fix these compilation errors:

1)

glfw/wl_init.c:653:5: error: use of undeclared identifier errno
    errno = ENOSYS;
    ^
glfw/wl_init.c:653:13: error: use of undeclared identifier ENOSYS
    errno = ENOSYS;
            ^
glfw/wl_init.c:639:25: error: unused parameter fd [-Werror,-Wunused-parameter]
get_socket_peer_pid(int fd) {
                        ^
3 errors generated.
 done
Compiling [wayland] glfw/wl_init.c ...
cc -MMD -DNDEBUG -DEPOLL_SHIM_DISABLE_WRAPPER_MACROS -I/usr/local/include/libepoll-shim -D_GLFW_WAYLAND -D_GLFW_BUILD_DLL -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-pro
tector-strong -pipe -fvisibility=hidden -fno-plt -fPIC -O2 -pipe -Wno-error=invalid-utf8 -Winvalid-utf8 -fstack-protector-strong -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -flto -I/usr/local/include -fcf-protection=full -fPIC -pthread -I/usr/local/include -I/usr/loc
al/include/libepoll-shim -I/usr/local/include -I/usr/local/include/libepoll-shim -I/usr/local/include -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -c glfw/wl_init.c -o build/glfw-wayland-glfw-wl_init.c.o
*** Error code 1

2)

[21/120] Compiling kitty/line.c ...
glfw/wl_client_side_decorations.c:809:19: error: use of undeclared identifier BTN_LEFT
    if (button == BTN_LEFT) {
                  ^
glfw/wl_client_side_decorations.c:846:24: error: use of undeclared identifier BTN_RIGHT
    else if (button == BTN_RIGHT) {
                       ^
2 errors generated.
 done
Compiling [wayland] glfw/wl_client_side_decorations.c ...
cc -MMD -DNDEBUG -DEPOLL_SHIM_DISABLE_WRAPPER_MACROS -I/usr/local/include/libepoll-shim -D_GLFW_WAYLAND -D_GLFW_BUILD_DLL -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-pro
tector-strong -pipe -fvisibility=hidden -fno-plt -fPIC -O2 -pipe -Wno-error=invalid-utf8 -Winvalid-utf8 -fstack-protector-strong -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -flto -I/usr/local/include -fcf-protection=full -fPIC -pthread -I/usr/local/include -I/usr/loc
al/include/libepoll-shim -I/usr/local/include -I/usr/local/include/libepoll-shim -I/usr/local/include -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -c glfw/wl_client_side_decorations.c -o build/glfw-wayland-glfw-wl_client_side_decorations.c.o
*** Error code 1

Release changes:	https://sw.kovidgoyal.net/kitty/changelog/#detailed-list-of-changes
Reported by:	portscout