graphics/mesa-devel: unbreak VAAPI/VDPAU after 117e00cbc3d2
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/dri%%SUFFIX%%/libgallium_drv_video.so
Error: Missing: lib/vdpau%%SUFFIX%%/libvdpau_gallium.so.1.0.0
===> Error: Plist issues found.
*** Error code 1

===>   Building mesa-devel-24.2.b.2418
pkg-static: Unable to access file /wrkdirs/usr/ports/graphics/mesa-devel/work/stage/usr/local/lib/dri-devel/libgallium_drv_video.so:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/graphics/mesa-devel/work/stage/usr/local/lib/vdpau-devel/libvdpau_gallium.so.1.0.0:No such file or directory
*** Error code 1

Reported by:	pkg-fallout
Regressed by:	https://gitlab.freedesktop.org/mesa/mesa/-/commit/212d57f7e670
Regressed by:	https://gitlab.freedesktop.org/mesa/mesa/-/commit/b6faf586e65b