net/samba419: Update version requirements for talloc
The configure step fails with the following message:

> Checking for system talloc (>=2.4.1) : not found
> ERROR: System library talloc of version 2.4.1 not found, and bundling disabled
> ===>  Script "configure" failed unexpectedly.

Update the required talloc version accordingly in the makefile.

PR:		280510, 280509
Sponsored by:	Klara, Inc.
Approved by:	portmgr blanket