net-im/prosody: Fix PLIST after mandir migration
====> Running Q/A tests (stage-qa)
Warning: Installing man files in /usr/local/man is no longer supported. Consider installing these files in /usr/local/share/man instead.
51537 drwxr-xr-x  3 root  wheel  64 Aug 19 19:46:14 2024 /wrkdirs/usr/ports/net-im/prosody/work/stage/usr/local/man
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir man/man1
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Approved by:	portmgr (blanket)