graphics/dcmtk: fix build with clang 19
Clang 19 now diagnoses incorrect member accesses, which causes
graphics/dcmtk to fail with a errors similar to:

    /wrkdirs/usr/ports/graphics/dcmtk/work/dcmtk-DCMTK-3.6.8/ofstd/include/dcmtk/ofstd/ofutil.h:79:18: error: no member named 'pt' in 'OFrvalue_storage<T, >'
       79 |         : t( rhs.pt ) {}
          |              ~~~ ^

Upstream dcmtk fixed this by changing the affected copy constructor in
https://github.com/DCMTK/dcmtk/commit/c29bebcd1, so pull this in as a
patch and apply it.

PR:		280865
Approved by:	yuri (maintainer)
MFH:		2024Q3