multimedia/ringrtc: Fix build on recent main
After src snapshot 0c47b9c211e, the build began failing with:

../../third_party/nasm/include/compiler.h:249:21: error: static
  declaration of 'mempcpy' follows non-static declaration
  249 | static inline void *mempcpy(void *dst, const void *src, size_t n)
      |                     ^
/usr/include/string.h:71:8: note: previous declaration is here
   71 | void    *(mempcpy)(void * __restrict,
                  const void * __restrict, size_t);

Fix the build by restoring a default definition of HAVE_MEMPCPY since
we have had mempcpy() since 13.1.

Approved by:	kevans, mikael (maintainer)
Sponsored by:	The FreeBSD Foundation
Differential Revision:	https://reviews.freebsd.org/D46053