devel/py-watchdog: Update to 4.0.2
- Mark a couple of tests as broken/ignored due to the following errors:

  * test_eventlet_monkey_patching (ignored):
    NotImplementedError: unsupported platform
    site-packages/trio/_core/_run.py:2843: NotImplementedError
  * test_observers_polling (broken):
    FileNotFoundError: [Errno 2] No such file or directory: /tmp/tmp*
    src/watchdog/utils/dirsnapshot.py:318: FileNotFoundError

Release changes:	https://github.com/gorakhargosh/watchdog/releases/tag/v4.0.2
Reported by:	Mickaël Schoentgen <notifications@github.com>