misc/py-oterm: Fix a runtime error
- Due to an incompatibility with the recent version of textproc/py-textual,
  oterm crashes when there are saved chats, with the following error

│ /usr/local/lib/python3.11/site-packages/textual/widget.py:984 in mount                                                                                                                                                                                                  │
│                                                                                                                                                                                                                                                                         │
│    981 │   │   if self._closing or self._pruning:                                               ╭──────────── locals ────────────╮                                                                                                                                      │
│    982 │   │   │   return AwaitMount(self, [])                                                  │   after = None                 │                                                                                                                                      │
│    983 │   │   if not self.is_attached:                                                         │  before = None                 │                                                                                                                                      │
│ ❱  984 │   │   │   raise MountError(f"Can't mount widget(s) before {self!r} is mounted")        │    self = TabPane(id='chat-1') │                                                                                                                                      │
│    985 │   │   # Check for duplicate IDs in the incoming widgets                                │ widgets = (ChatContainer(),)   │                                                                                                                                      │
│    986 │   │   ids_to_mount = [                                                                 ╰────────────────────────────────╯                                                                                                                                      │
│    987 │   │   │   widget_id for widget in widgets if (widget_id := widget.id) is not None                                                                                                                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
MountError: Can't mount widget(s) before TabPane(id='chat-1') is mounted

So add the patch patch-oterm_app_oterm.py, that is a simple workaround
waiting for an official solution by upstream.

- Bump PORTREVISION